replicaCount: 2

image:
  repository: ghcr.io/al-gorceries-2/al-gorceries-2-ui
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: www.al-gorceries.com
  annotations:
    kubernetes.io/ingress.class: traefik
